theme = "slick"
#theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 120
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "sound"

[[block]]
block = "battery"

[[block]]
block = "temperature"

[[block]]
block = "net"
device = "wlp3s0"
ssid = true
ip = false
speed_up = false
speed_down = true
graph_down = false
interval = 5

[[block]]
block = "time"
interval = 10
format = "%a %d/%m %R"
